### ISSUE TITLE
Packet size & small embedded systems

### ISSUE THREAD

**Issue by jpf91** [noisesocket/spec#1]
Hi,

As far as I understand it's not possible to decrypt (or rather authenticate) a partial packet in noise protocols. This means a receiving end always needs to cache the complete incoming packet. With maximum packet sizes of `65535=64kB` most embedded systems couldn't handle even one stream.

I was wondering whether we could implement some smart solution. Of course when an embedded system talks to another embedded system both will likely use small send buffers as well and therefore communication should be possible with small read buffers. But for PC<=>embedded communication the PC might send a 64kB packet to some client which can't handle this. How does TLS work in this regard?

I guess partial decoding of the stream is a possibility, but as the authentication can only be accomplished once a complete packet has been received this places quite some burden on the user to not do anything important with partial unauthenticated data.

**Comment by Scratch-net** [comment]
We thought about some API setting that could limit the size of packets, but anyway this is something that the sending party should be doing. Other than that it’s very easy to implement

**Comment by jpf91** [comment]
> We thought about some API setting that could limit the size of packets, but anyway this is something that the sending party should be doing. Other than that it’s very easy to implement 

I guess the main question is at which layer to include this. As far as I understand at some layer the packet based noise protocol needs to be adapted to a stream-like socket layer. Such a layer can't require general purpose higher layers to manually manage packet sizes. So the question is whether this translation layer should be in the noise socket protocol. I'd argue this should be considered if noise socket wants to be a drop in replacement for TLS.

> We thought about some API setting that could limit the size of packets, but anyway this is something that the sending party should be doing

Consider one of the most famous TLS protocols, https. If https were built with noise socket and the packet size is a server/sending party API setting, then most big server machines would probably use the maximum packet sizes (enough ram, save some overhead). This would be fine for normal PC web browsers.
But then there are devices that could easily stream a http stream (e.g. to an audio output for web radio) but can't buffer 64kB. With a sender-only API setting these applications are not possible with noise socket.

Maybe a transparent protocol level buffer size negotiation adds too much complexity to the protocol, but I think this is something that should be considered.

**Comment by Scratch-net** [comment]
Actually with the addition of message fields (see spec https://github.com/noisesocket/spec/blob/master/noise_socket.md) we could add a field limiting the maximum packet size.

There will for sure be a place in the code where incoming bytes are split into packets and limiting the packet size code should go right there.

 

Is this something we want in v1? Should the support of this feature be a must or an option?

**Comment by jpf91** [comment]
> Actually with the addition of message fields (see spec https://github.com/noisesocket/spec/blob/master/noise_socket.md) we could add a field limiting the maximum packet size. There will for sure be a place in the code where incoming bytes are split into packets and limiting the packet size code should go right there. 

Sounds great 👍 

> Is this something we want in v1? Should the support of this feature be a must or an option?

I think embedded systems could really benefit from some safe communication. We already have TweetNacl and AVRNaCl for small controllers so this seems to be a feasible target for noise sockets. So I'd say V1: yes; required or optional seems both possible.

**Comment by jpf91** [comment]
The updated spec looks great.

Some unrelated, probably stupid question: Why are the packet sizes preceding the payloads not encrypted (MAC adds to much overhead of course, but simple encryption?). Wouldn't encryption of these sizes make it more difficult to analyze these streams?

**Comment by Scratch-net** [comment]
@jpf91 Sizes are unenecrypted because the following message is always mac-authenticated, we don't even need to include the size into additional data. Also, encrypting size seems like an overhead

**Comment by jpf91** [comment]
Indeed.

I was mainly concerned that a firewall with deep packet inspection could monitor the handshake and then follow the complete exchange of packets as the sizes are unencrypted. So the data is completely encrypted but packet size / frequency is detectable. OTOH this information will be partly available in TCP packet sizes anyway...
